branch-defaults:
  default:
    environment: eb-rails-dev
    group_suffix: null
global:
  application_name: eb-rails
  branch: null
  default_ec2_keyname: eb-virginia
  default_platform: Ruby 3.0 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
