default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:development, :postgres_username) %>
  password: <%= Rails.application.credentials.dig(:development, :postgres_password) %>
  host: localhost

development:
  <<: *default
  database: my_app_rails_eb_development

test:
  <<: *default
  database: my_app_rails_eb_test

production:
  <<: *default
  database: my_app_rails_eb_production
  username: my_app_rails_eb
  password: <%= ENV['DATABASE_PASSWORD'] %>
